# Generated by Django 4.0.4 on 2022-05-27 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(max_length=70)),
                ('curso', models.CharField(max_length=60)),
                ('topicos', models.CharField(default='1', max_length=500)),
                ('local', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(default='1', upload_to='static/portfolio/images')),
                ('logotipo', models.ImageField(upload_to='static/portfolio/images')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('descricao', models.TextField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, upload_to='static/portfolio/images')),
                ('autor', models.CharField(max_length=40)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('texto', models.TextField(max_length=1000)),
                ('imagem', models.ImageField(upload_to='static/portfolio/images')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('linklusofona', models.CharField(default='1', max_length=1000)),
                ('linklinkedin', models.CharField(default='1', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('apelido', models.CharField(max_length=20)),
                ('pontuacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('acronimo', models.CharField(blank=True, max_length=10)),
                ('ano', models.IntegerField()),
                ('criador', models.CharField(max_length=40)),
                ('logotipo', models.ImageField(upload_to='static/portfolio/images')),
                ('link', models.CharField(max_length=500)),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('sumario', models.TextField(max_length=1000)),
                ('linkGitHub', models.CharField(max_length=1000)),
                ('linkYoutube', models.CharField(max_length=1000)),
                ('linkRelatorio', models.CharField(max_length=1000)),
                ('ano', models.IntegerField()),
                ('autor', models.CharField(max_length=70)),
                ('orientador', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='static/portfolio/images')),
                ('participantes', models.CharField(max_length=100)),
                ('cadeira', models.CharField(max_length=40)),
                ('ano', models.IntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('linkgithub', models.CharField(blank=True, max_length=1000)),
                ('tecnologia', models.ManyToManyField(to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('descricao', models.TextField(max_length=1000)),
                ('ects', models.IntegerField()),
                ('ano_letivo', models.CharField(default='1', max_length=20)),
                ('topicos_abordados', models.CharField(default='1', max_length=1000)),
                ('ranking', models.IntegerField()),
                ('link_cadeira', models.CharField(default='1', max_length=1000)),
                ('docente_teorica', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='portfolio.person')),
                ('docentes_praticas', models.ManyToManyField(related_name='professor_pratica', to='portfolio.person')),
                ('linguagens', models.ManyToManyField(blank=True, to='portfolio.tecnologia')),
                ('projetos', models.ManyToManyField(blank=True, to='portfolio.project')),
            ],
        ),
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='1', max_length=70)),
                ('descricao', models.CharField(default='1', max_length=100)),
                ('cadeira', models.CharField(default='1', max_length=40)),
                ('projetos', models.ManyToManyField(blank=True, to='portfolio.project')),
            ],
        ),
    ]
