# Generated by Django 4.0.4 on 2022-05-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='existente',
            field=models.BooleanField(default=False),
        ),
    ]
