# Generated by Django 4.0.4 on 2022-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tecnologia_existente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfc',
            name='imagem',
            field=models.ImageField(default='1', upload_to='static/portfolio/images'),
        ),
    ]
