# Generated by Django 4.0.4 on 2022-06-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_tfc_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfc',
            name='orientador',
        ),
        migrations.AddField(
            model_name='tfc',
            name='orientador',
            field=models.ManyToManyField(to='portfolio.person'),
        ),
    ]
