# Generated by Django 4.0.4 on 2022-06-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_tfc_orientador_tfc_orientador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/portfolio/images'),
        ),
    ]
