# Generated by Django 4.0.4 on 2022-06-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_tfc_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/portfolio/images'),
        ),
    ]
